apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pv
  labels:
    store: dags
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: # Add the efs file location for Bikash to edit fs-xxxxxxxx:/var/lib/airflow/dags